### ISSUE TITLE
DxcCheckbox - No animation on Hover

### ISSUE THREAD

**Issue by NorbertPointu** [dxc-technology/halstack-style-guide#127]
Describe the solution you'd like
Minor : No animation on hover - for example to indicate it is selectable

Have animation to help user
https://material.io/components/checkboxes#behavior

**Comment by aweell** [comment]
Hello @NorbertPointu,

We agree that adding a hover state could improve the usability of the component. Your feedback will be added to the component review. I set the issue status as "waiting for review" until then.

**Comment by aweell** [comment]
Hi @NorbertPointu,

Checkbox `:hover` state its already changing the color of our checkbox component.

![Screen Shot 2021-09-23 at 5 30 42 PM](https://user-images.githubusercontent.com/44420072/134537581-ec897d96-862d-465d-8c97-5e0b9aba3b16.png)

_Checkbox:hover on the left, enabled on the right_

An update of the color to a darker blue variant in order to improve contrast has been added to the [component documentation](https://github.com/dxc-technology/halstack-style-guide/tree/master/guidelines/components/checkbox) in 3.8.0.

You can track the implementation in the CDKs through the following issues:

* https://github.com/dxc-technology/halstack-react/issues/380
* https://github.com/dxc-technology/halstack-angular/issues/425
