### ISSUE TITLE
Regarding theme tokens restrictions in style guidelines

### ISSUE THREAD

**Issue by SavvySparrow** [dxc-technology/halstack-style-guide#14]
As per [Style Guidelines,](https://developer.dxc.com/design/components) one can not change any component font color from default #000000.

But due to this new guidlines, it would be difficult to create any dark version of any theme _(white font color and dark body background)_ . I mean the whole idea of Theme tokens is to change the component color theme as per our needs without changing the technical details like height,width etc

The tokens are already there but due to new guidelines, there is restriction to override non themable tokens like label color or font color of input component, that means we can create different theme with only `white body background` always.

cc: @peibolsang @jsardid

**Comment by jsardid** [comment]
@SavvySparrow You can change the text color of most components, specially if they have a themeable token for the background. Take the button as an example:
https://developer.dxc.com/design/components/button

If you find missing themeable tokens, please create issues for each of them and let's discuss them separately, since the reasons why they were not included in the first place might differ. 

Thanks.
