### ISSUE TITLE
[Checkbox] Component specs

### ISSUE THREAD

**Issue by mnnaveenk** [dxc-technology/halstack-style-guide#143]
Design Specifications
----------------------

| Property | Value |
|--|--|
| Margin right/left | 15px |
| Margin top/bottom | 10px |
| Border Radius | 4px |
| Border thickness | 2px |
| Font size (with text) | 16px |
| Font weight | Regular |

Margin left/tight [**image**]: 12px

**Comment by aweell** [comment]
Hello @mnnaveenk,

The value presented in the documentation images refers to the `padding` instead of the `margin`

Regarding margin values:

The design specs set the value for `margin-right/left` as 15px and the `margin-top/bottom` as 10px, the implementation gives the flexibility to choose between different values: 

margin | value
-- | --
```xxsmall``` | 6px
```xsmall``` | 16px
```small``` | 24px
```medium``` | 36px
```large``` | 48px
```xlarge``` | 64px
```xxlarge``` | 100px

- [ ] Design guidelines should be updated to accommodate the possibility to use different `margin` values.
