### ISSUE TITLE
Value selection in Dropdown

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-style-guide#249]
When we are tabbing the fields and focus coming on a Select box. Now the requirement is without clicking the down arrow on the keyboard, when ‘T’ is selected on keyboard -  Texas should come on the field. 

Please let us know, of this can be achieved?

You can try on the QuoteInfo Screen from below link.
https://new-business.dev-835.hub-1.sandbox.assure.dxc.com/#/

**Comment by aweell** [comment]
Hello @ppurumala,

From the WAI-ARIA practices 1.2 -  [3.14 Listbox](https://www.w3.org/TR/wai-aria-practices-1.2/#listbox_kbd_interaction):

> **Keyboard interaction** 
> 
> * Type a character: focus moves to the next item with a name that starts with the typed character.
> * Type multiple characters in rapid succession: focus moves to the next item with a name that starts with the string of characters typed.

The options list needs **always to be open** in order to move the focus to the next item using the **type-ahead** feature. 

Let's see this through an example:

If the options list has more than one element starting with the "T" which one should be selected? (e.g. Texas, Tennesee). Having the list opened the focus will move to the first item "Tennesee", pressing "T" again will move to "Texas" so the user can choose which item starting with "T" wants to select.

I Hope this solves your question 😉 !

**Comment by ppurumala** [comment]
wanted to know where is the type-ahead feature? is this something component has already or we have to implement that separately?

**Comment by aweell** [comment]
Hi @ppurumala,

It is possible to move focus to a list item by typing a character in our [select](https://developer.dxc.com/tools/react/3/#/components/select) and our [dropdown](https://developer.dxc.com/tools/react/3/#/components/dropdown) components.

**Comment by aweell** [comment]
Closing the issue since it seems solved
