### ISSUE TITLE
When we make a select-box and inputbox/textarea disable, the text is very faintly visible

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-style-guide#34]
When we make a select-box and inputbox/textarea disable, the text is very faintly visible

we have a input box and select box, when we mark them as disabled, the text color is very much greyish and with white background, the text is hard to read.  Please refer below image.

We would please like bit darker text color, so that we can read the text easily.

![textNoVisible](https://user-images.githubusercontent.com/72923647/110486007-3a279880-8112-11eb-9b9f-f67037acf683.jpg)

**Comment by aweell** [comment]
Hello @ppurumala,

Please provide more context so we can consider how "meaningful in his disabledness" this information is or a different approach rather than using the disabled component state if the information needs to be read.

Following the [1.4.3 WCAG 2.0 Success criterion](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html):

> Contrast (Minimum): 
> 
> Incidental: Text or images of text that are part of an inactive user interface component, that are pure decoration, that are not visible to anyone, or that are part of a picture that contains significant other visual content, have no contrast requirement.

A disabled state falls in the category of an inactive user interface component.

**Comment by ppurumala** [comment]
In the DXCInput field, put an attribute  disabled="true". 
Basically we dont want the user to change that value. So we want the text to still readable, but is very light colored, so difficult to read.

**Comment by aweell** [comment]
Thanks, @ppurumala, input components are planned to be reviewed. Until we accomplish that roadmap task we recommend the following:

> Text type content (subject to editing actions):
> 
> Typographic content that may be the subject of an editing action must be displayed as plain text until the moment the user performs the action.
> 
> At the moment the action is performed the input component must be shown with the content available for editing.

The disabled attribute prevents any interaction with the element. 

Regarding accessibility:

- The input will not have a tab stop. Navigation through the keyboard or any other kind of peripheral device rather than a mouse would be affected.
- Disabled components can't cave focus, screen readers won't know that this information is there.
