### ISSUE TITLE
Font size of labels on an input box, should be larger when data is entered.

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-style-guide#53]
**Describe the bug**
Font size of labels on an input box, should be larger when data is entered. The font is very 

**To Reproduce**
Font size on label at top of entered data in input box is hard to read when the user starts typing into the entry field and the label moves to the top.

**Expected behavior**
Team is requesting the size to bit bigger than current

**Screenshots**
![spacingIssue](https://user-images.githubusercontent.com/72923647/114161879-26a46300-9946-11eb-88c8-244d8564e92f.jpg)

Please revert incase more data is required.

**Comment by aweell** [comment]
Regarding `input-text` label readability:

The minimum size recommended to ensure readability is (depending on the author) in the range from 9pt (±12px) to 10pt (±13px), the font sizes used are:

Font size (enabled) | 16px
-- | --
Font size (active] | 12px

Although [this study](
http://pielot.org/pubs/Rello2016-Fontsize.pdf) presents how the increase of the can optimize readability. We need to think about how the user behaves when reading and interacting with this kind of text-based component.

In order to understand the required data, the user reads the label in the enabled mode (16px). The active mode focus in the data entered showing the label on top as a "helper text" with a `font-size` of 12px, as commented enough to ensure readability.

From the study:

> "Jakob Nielsen suggests using 10 points as minimum font size." 

Since the label in the enabled mode is 16px (12pt) we're covering the minimum size suggestion from usability experts.

Regarding accessibility:

[WACG 2.0 - SC 1.4.4](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-scale.html)

> "If the author is using a technology whose user agents do not provide zoom support, the author is responsible to provide this type of functionality directly or to provide content that works with the type of functionality provided by the user agent."

If the application is working in an environment that has zoom support (min 200%) the component is compliant with the success criterion.

> Content satisfies the Success Criterion if it can be scaled up to 200%, that is, up to twice the width and height. Authors may support scaling beyond that limit, however, as scaling becomes more extreme, adaptive layouts may introduce usability problems.

Since we consider that there is no issue related to readability regarding the `input-text` labels. We set this issue as closed and we take this feedback for the future review of this particular component.
