### ISSUE TITLE
Option to remove company logo from the footer

### ISSUE THREAD

**Issue by ppurumala** [dxc-technology/halstack-style-guide#9]
Since in the header we already have the company logo, our business stakeholders don't want company logo from the footer.

Below is the footer which we have currently.

![Current Footer](https://user-images.githubusercontent.com/72923647/100228564-df927400-2f48-11eb-97fa-3dbdc4f48d21.JPG)

Please tell if you can achieve this footer design or not possible to achieve?

The size of the footer is given as 120px hardcoded. We would not like such a big footer, as it occupies too much real estate on the views. and restricting us from creating views without scrolling. 
can it be given upto developer for the size configuration.

**Comment by pwadhwani** [comment]
Hi Team, Please update when can we have this feature.

**Comment by peibolsang** [comment]
This issue is under investigation with our UX Design team as it may not be a problem with the footer itself. If the footer is visible from your splash screen as the user arrives, it may be a problem with your splash screen. It should not be visible.

As stated in these [Adobe XD guidelines](https://xd.adobe.com/ideas/principles/app-design/examples-and-benefits-of-a-mobile-app-splash-screen/) the size of the splash screen is important and you should develop your App taking different mobile sizes into consideration. The objective is to make your splash screen (header+picture) to fill the mobile screen so the footer is not visible in the first place

**Comment by peibolsang** [comment]
We are investigating the removal of the logo.

For the size of the footer, a decision has been made: The footer complies with the size established by the designer. It is not a problem with the footer. As commented in the Adobe XD guidelines, @pwadhwani and @ppurumala you need to make implement your landing screen in such a way that the footer **is not** visible. You need to adapt the size of header+main so that it fulfills the mobile screen.

**Comment by ppurumala** [comment]
Please share, if you have any update on removal of logo from footer.

**Comment by ppurumala** [comment]
Please share, if you have any update on removal of logo from footer.

**Comment by aweell** [comment]
Hello @ppurumala,

Regarding the removal of the logo footer:

- From the user point of view, is the brand presence in the footer a blocker to perform any task?
- From the UX perspective, how the presence or absence of the brand image can improve the overall user experience of the site?
- From the business perspective, which business problem in the scope of the project solves the removal of the brand image?

Since images are an effective way to reinforce the brand, the footer is a good place to use an alternate version of the logo differently.

In the next update of the footer documentation:

> "We recommend uploading either an alternate version or a smaller brand image than the used in the header. If the company has an alternate version of the logo, isotype, imagotype or isologo available, we encourage them to use it. In the opposite case, a smaller version of the main brand image can be used."

We strongly believe that answering the previous questions should clarify the matter before taking any design decision.

**Comment by pwadhwani** [comment]
Business has agreed upon new design by UX designer so currently we don't require this functionality.
