### ISSUE TITLE
[Application layout] Documentaion update

### ISSUE THREAD

**Issue by GauravMaurya0** [dxc-technology/halstack-style-guide#97]
There is no application layout with side naviation , 2 column layout, symmetrical layout components.
Alignment issues. 

![Picture1](https://user-images.githubusercontent.com/75359999/115824635-de953e00-a425-11eb-98c1-413392748eb1.png)

**Comment by aweell** [comment]
Thanks @GauravMaurya0,

An example of application layout with sidenav can be found in any of the implementation sites:

* [Angular](https://developer.dxc.com/tools/angular/3/#/components/applicationLayout)
* [React](https://developer.dxc.com/tools/react/3/#/components/applicationLayout)

The main container is a free box where any content can be included, since we don't provide any tool to build columns layouts it's a recommendation for the end Designer/Developer.

Add more information about the alignment issues you comment on.

**Comment by GauravMaurya0** [comment]
**Specifications for the layout:**
Sidenav: 300 pixels (width), 100% (height)
Main content margins for desktop: 64 pixels (top), 80 pixels (bottom), 8.6% (right), 5.4% (left)
Main content margins for tablet: 48 pixels (top), 64 pixels (bottom), 9.6 (left/right)
Main content margins for mobile: 36 pixels (top), 48 pixels (bottom), 6.4% (left/right)

**Application Layout with secondary aside navigation**
Aside: 88 pixels (width), 100% (height)

**Content Layout**
Two column layout
There should be a relationship aspect between the two columns, to preserve size and scaling. So we can establish a rule going from 1/4 to 3/4 where, 1/4 is the minimum value that a column can take and 3/4 is the maximum value to be expanded by one single column.
Accordingly, the other column should take the rest of available space based on the ratio selected for each of them, making the 100% of the screen width.

**Symmetrical layout**
Specifications for paired layout:
- Main margin for desktop: 64 pixels (top), 80 pixels (bottom), 15.6% (left/right)
- Side columns: 270 pixels (width), 64 pixels (margin top), 80 pixels (margin bottom)

**Comment by aweell** [comment]
Hello @GauravMaurya0,

We are discussing the possibility of adding more examples to the CDK sites. Until then since the application layout can have any child, we consider there's not any design issue.
